/**
 * Public Report Route — Renders a session's markdown report as a
 * standalone HTML page that can be shared without authentication.
 *
 * GET /api/sessions/[sessionId]/public
 */

import { NextResponse } from "next/server";
import { generateSessionExport } from "@/lib/export";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ sessionId: string }> }
) {
  try {
    const { sessionId } = await params;
    const { markdown } = await generateSessionExport(sessionId);

    // Convert markdown to basic HTML
    const html = renderMarkdownPage(markdown, sessionId);

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "public, max-age=300",
      },
    });
  } catch {
    return new NextResponse(
      "<html><body><h1>Report not found</h1><p>This review may not exist or hasn't completed yet.</p></body></html>",
      { status: 404, headers: { "Content-Type": "text/html" } }
    );
  }
}

function renderMarkdownPage(md: string, sessionId: string): string {
  const bodyHtml = simpleMarkdownToHtml(md);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Review Report</title>
  <style>
    :root { color-scheme: dark; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #0f0f14;
      color: #e4e4e7;
      max-width: 720px;
      margin: 0 auto;
      padding: 2rem 1.5rem;
      line-height: 1.6;
    }
    h1 { color: #f4f4f5; font-size: 1.5rem; margin-bottom: 0.5rem; }
    h2 { color: #a78bfa; font-size: 1.1rem; margin-top: 2rem; border-bottom: 1px solid #27272a; padding-bottom: 0.4rem; }
    h3 { color: #d4d4d8; font-size: 0.95rem; margin-top: 1.5rem; }
    blockquote {
      border-left: 3px solid #a78bfa;
      background: #18181b;
      padding: 0.75rem 1rem;
      margin: 1rem 0;
      border-radius: 0.375rem;
    }
    a { color: #a78bfa; text-decoration: none; }
    a:hover { text-decoration: underline; }
    code { background: #27272a; padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.85em; }
    pre { background: #18181b; padding: 1rem; border-radius: 0.5rem; overflow-x: auto; }
    pre code { background: none; padding: 0; }
    ul, ol { padding-left: 1.5rem; }
    li { margin-bottom: 0.3rem; }
    strong { color: #f4f4f5; }
    hr { border: none; border-top: 1px solid #27272a; margin: 1.5rem 0; }
    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #27272a; font-size: 0.8rem; color: #71717a; }
  </style>
</head>
<body>
  ${bodyHtml}
  <div class="footer">
    Generated by <strong>Movistan</strong> AI Code Review ·
    <a href="/sessions/${sessionId}/results">View interactive report</a>
  </div>
</body>
</html>`;
}

/** Minimal markdown → HTML converter (no external deps). */
function simpleMarkdownToHtml(md: string): string {
  return md
    .split("\n")
    .map((line) => {
      // Headers
      if (line.startsWith("### ")) return `<h3>${esc(line.slice(4))}</h3>`;
      if (line.startsWith("## ")) return `<h2>${esc(line.slice(3))}</h2>`;
      if (line.startsWith("# ")) return `<h1>${esc(line.slice(2))}</h1>`;
      // Blockquote
      if (line.startsWith("> ")) return `<blockquote>${inline(line.slice(2))}</blockquote>`;
      // Horizontal rule
      if (/^---+$/.test(line.trim())) return "<hr />";
      // List items
      if (/^(\d+)\.\s/.test(line)) return `<li>${inline(line.replace(/^\d+\.\s/, ""))}</li>`;
      if (line.startsWith("- ")) return `<li>${inline(line.slice(2))}</li>`;
      if (line.startsWith("  - ")) return `<li style="margin-left:1rem">${inline(line.slice(4))}</li>`;
      // Empty line
      if (line.trim() === "") return "<br />";
      // Paragraph
      return `<p>${inline(line)}</p>`;
    })
    .join("\n");
}

function inline(text: string): string {
  return esc(text)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>');
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
